name: Test Repo Vars Update

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Your name"
        required: false
        default: "Test User"

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Increment Variable
      run: |
        echo "Hello ${{ inputs.user_name }}!"
        cat test_file.txt
        echo "Current Value of TEST_NUMERIC_VAR is ${{ vars.TEST_NUMERIC_VAR }}"
        VAR_VALUE = ${{ vars.TEST_NUMERIC_VAR }}
        VAR_VALUE = $((VAR_VALUE + 1))
        echo "Current Value of TEST_NUMERIC_VAR is $VAR_VALUE"
