name: Test Repo Vars Update

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Your name"
        required: false
        default: "Test User"

env:
  GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Increment Variable
      run: |
        echo "Hello ${{ inputs.user_name }}!"
        cat test_file.txt
        VAR_VALUE=${{ vars.TEST_NUMERIC_VAR }}
        VAR_NAME="TEST_NUMERIC_VAR"
        echo "Current Value of TEST_NUMERIC_VAR is $VAR_VALUE"
        UPDATED_BUILD_NUMBER=$((VAR_VALUE+1))
        CURRENT_MARKETING_VERSION="2.1.2"
        echo "Updated Value of TEST_NUMERIC_VAR is $UPDATED_BUILD_NUMBER"
        echo "${{ github.event.repository.owner }}/${{ github.event.repository.name }}"
        echo "${{ github.repository }}"
        gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/variables/$VAR_NAME \
            -f name=$VAR_NAME \
            -f value=$UPDATED_BUILD_NUMBER

        curl --location 'https://us-central1-credprod-217806.cloudfunctions.net/triggerIPA/github-build-status' \
          --header 'Authorization: 045ec05c2c684a149dc7ad1e03ebb3216d178ebf0f5e48669b9376cc64d92904' \
          --header 'Content-Type: application/json' \
          --data '{
              "build_progress": "RUNNING",
              "workflow_url": "${{ env.WORKFLOW_URL }}",
              "thread_id": "${{ github.event.inputs.thread_id }}",
              "channel_id": "${{ github.event.inputs.channel_id }}",
              "build_version": $CURRENT_MARKETING_VERSION,
              "build_number": $UPDATED_BUILD_NUMBER
            }'
