name: Test Repo Vars Update

on:
  workflow_dispatch:
    inputs:
      user_name:
        description: "Your name"
        required: false
        default: "Test User"

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Increment Variable
      env:
        GH_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        echo "Hello ${{ inputs.user_name }}!"
        cat test_file.txt
        VAR_VALUE=${{ vars.TEST_NUMERIC_VAR }}
        echo "Current Value of TEST_NUMERIC_VAR is $VAR_VALUE"
        UPDATED_VALUE=$((VAR_VALUE+1))
        echo "Updated Value of TEST_NUMERIC_VAR is $UPDATED_VALUE"
        echo "${{ github.event.repository.owner }}/${{ github.event.repository.name }}"
        echo "${{ github.repository }}"
        gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/variables/TEST_NUMERIC_VAR \
            -f name='TEST_NUMERIC_VAR' \
            -f value=$UPDATED_VALUE
